services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: student-risk-api:latest.2
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_ARTIFACT_ROOT: /app/mlruns
    volumes:
      - ./mlruns:/app/mlruns:ro
    depends_on:
      - mlflow

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    image: student-risk-mlflow:v1.1
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
