on:
  push:
    branches:
    -  main


jobs:  
  Tester:
    runs-on: ubuntu-latest

    steps:
    -  name:  Checkout repository
       uses:  actions/checkout@v7

    -  name:  Setup python
       uses:  actions/setup-python@v7

       with:
         python-version: '3.12'
         
    -  name: Install dependencies
       run: |   
           sudo apt update
           sudo apt install python3-pip -y
           pip install -r requirements.txt

    -  name: Testing API
       run: python -m pytest -s
